### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0NiwibmFtZSI6IkFVUkVMSU5PIiwiZW1haWwiOiIxMTEyMDIyMTQxNjJAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTY2OTQwLCJleHAiOjE3ODEwNTMzNDB9.KR88vieV2XO6ha7FOAtpIHw95CBKlVeuAxkykxjY2bc

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer xxx

{
  "target_amount": 5000,
  "present_amount": 2100
}